version: '3.8'

services:
  tracking-transactions:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhone17/tracking-transactions
    container_name: tracking-transactions
    restart: always
    ports:
      - '${PORT}:${PORT}'

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      STATE: ${STATE}
      HOST_CLIENT: ${HOST_CLIENT}
